### ISSUE TITLE
Error: MAPI property has an unsupported type and can not be retrieved

### ISSUE THREAD

**Issue by HeikoWatz** [datenteiler/ReadMsgFile#2]
I got some problems with your very nice tool.
I use it often to get the properties of MSG Files and sometimes I get some problems with it.
Now I get the Error: MAPI property has an unsupported type and can not be retrieved.
I found some solutions for this error, but I can’t resolve it because I’m not a developer and my C# Know-how is only rudimental.
I think this is a bug in your App or in the tools you are using.

I hope you can help me soon.

Thank you.

Heiko

**Comment by datenteiler** [comment]
Can you give more details: When does the error occur? With which MSG files? What is the exact error message? Which solutions have you already found where? 

I would be happy if I can fix it.

Best,
Christian

**Comment by HeikoWatz** [comment]
I get the message when i try to get the properties from an e-mail with read-msgfile:
```
PS H:\> Read-MsgFile $LocalPath -Verbose
Read-MsgFile : MAPI property has an unsupported type and can not be retrieved.
In Zeile:1 Zeichen:1
+ Read-MsgFile $LocalPath -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Read-MsgFile], ApplicationException
    + FullyQualifiedErrorId : System.ApplicationException,MsgFiles.ReadMsgFile
```
No more informations.

I do a google serach with this error Message and get some result with an C# Problem - as example:
https://stackoverflow.com/questions/31271932/c-sharp-problems-getting-a-specific-named-mapi-property-from-a-msg
https://github.com/Sicos1977/MSGReader/issues/90

Sorry - i can't give you the msg-file because it is internal.

Thank you for your help

Heiko

**Comment by datenteiler** [comment]
Hi Heiko,

I've updated the Cmdlet with the latest version of MSGReader 3.9.4. Can you test the Cmdlet?

Thank you.

Regards
Christian

**Comment by HeikoWatz** [comment]
Hi Christian,

I tested my problem and it is solved now.
Now the results are also much better than bevor. The Email addresses are now in a better format and not html like.

Thank you for the update and the help.

Regards 

Heiko
