### ISSUE TITLE
 System.Drawing is not supported on this platform

### ISSUE THREAD

**Issue by HeikoWatz** [datenteiler/ReadMsgFile#3]
I got some problems with your very nice tool.
I use it often to get the properties of MSG Files and now i get the errormessage:
"System.Drawing is not supported on this platform"

I do a serch and found these article:
https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only

I hope you can solve this problem.
Thank you.

**Comment by datenteiler** [comment]
I've build a version 2.0 with .NET 7 for PowerShell 7 what doesn't need "System.Drawing":

Install-Module -Name ReadMsgFile -RequiredVersion 2.0 -Scope CurrentUser

Does it work now?

**Comment by HeikoWatz** [comment]
Thank you very much – it is working fine with PowerShell 7.
But I use your command with PowerShell Version 5.1 which I can’t update at the moment.
It is possible to get a built for the old version of PowerShell?

**Comment by datenteiler** [comment]
Rebuild the Module with netstandard2.0 and PowerShellStandard.Library 5.1.1

Should work now in ReadMsgFile 2.1 with Windows Powershell 5 and PowerShell 7. Can you confirm?

**Comment by HeikoWatz** [comment]
It works with PowerShell 7 and Version 2.1.
But when i test it with Powershell 5.1.1 i get an error:

Read-MsgFile : Could not load file or assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the 
file specified.
At line:1 char:1
+ Read-MsgFile "C:\xxx\xxx.msg"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Read-MsgFile], FileNotFoundException
+ FullyQualifiedErrorId : System.IO.FileNotFoundException,MsgFiles.ReadMsgFile

In the meantime i switched in my PowerShell 5 Skript to a PS 7 Command

**Comment by datenteiler** [comment]
No Problem here with Windows PowserShell 5.1 and Windows Server 2019:

![grafik](https://user-images.githubusercontent.com/3180008/204562048-6b3a34a0-6308-499c-a1c1-0e14c571f5d4.png)

But I will check.
